### ISSUE TITLE
System for plugin authors to register renderers

### ISSUE THREAD

**Issue by Korla** [wrido/wrido#14]
- List view
- Details view
- More?

Are renderers registered per item in the result, or per resource in an item?

**Comment by pardahlman** [comment]
Perhaps wrido should be responsible to render the list view so that the items it it follows a consistent style? For example it could use the `title`, `description` and `image` (and perhaps `url` - not all items have this property) to create the listing.

**Comment by Korla** [comment]
Sounds good, this starts to feel lika a specification for the Query results. We also need some type for the DetailsResult. So something like this:

interface IListItemResult<T> {
  title: string;
  description: string;
  iconUrl: string; (iconId, imageUrl, imageId?); // Some url to the resource API
  detailsResult: IDetailsResult<T>; (?) // Optional details data perhaps, otherwise fetched on demand?
}

interface IDetailsResult<T> {
}

**Comment by pardahlman** [comment]
I think that the base class for `QueryResult` holds some common properties, like `Title`, `Description` and `Icon` (possibly more, like `Renderer`).

If a plugin needs more specific properties in the query response, the plugin author creates a derived result class

```csharp
  public class PluginResult : QueryResult
  {
    public string PluginProperty { get; set; }
  }
```

This, in turn, will be passed all the way up to front end, where it will materialize as a json object

```json
{
  "title" : "result title",
  "description" : "result description",
  "pluginProperty" : "plugin specific prop"
}
```

Makes sense?

**Comment by Korla** [comment]
That would also work. I tend naturally towards composition over inheritance personally, so instead of the PluginResult **being** a QueryResult, I think that the QueryResult **has** a PluginResult. 

If we go the inheritance route plugin authors might get in trouble down the line where they need to change their derived Query implementations since we added more metadata to the QueryResult.

**Comment by pardahlman** [comment]
I think there are pros and cons with both approaches. Either way, I don't think we need to make a decision today. A plugin author who wants to keep plugin specific data in a separate property can do so

```csharp
  public class PluginResult : QueryResult
  {
    public PluginPoco DetailsResult{ get; set; }
  }
```
which essentially would be the same implementation as something implementing `IListItemResult<PluginPoco>`. After all, it is the plugin author who will create the result object and write the renderer, so wrido as an application don't need to worry about this.

**Comment by pardahlman** [comment]
Closing this, as we have a first stab of registering plugins and renderers
