### ISSUE TITLE
Terminology?

### ISSUE THREAD

**Issue by pardahlman** [wrido/wrido#15]
I've been thinking about the terminology we are using for the different entities in wrido. Currently, the user input results in a `Query` and the query results in a list of `QueryResult` (base class) that is derived by plugins (like `GoogleResult` etc).

Is this right? I mean, it is obviously a query and a result for google searches, but how about the `:timer`? In that case it is more of a... command?

We should think this through and then make sure that the right terms is used everywhere.

**Comment by Korla** [comment]
One is a Write, the other is a Do ;)

The terms which feel applicable are all more diffuse to me, such as Action, or Event. How about Request, and Response?

**Comment by pardahlman** [comment]
But of course 😂 

The problem I'm having with _request_ and _response_ is that it sounds very http:ish which implicitly implies things (client initiated, status codes, cookies, ...).

If we don't want to put any specific meaning to whatever is written in the input (such as _query_ or _command_) then perhaps something along the line of `UserInput` and `Suggestion` would fit... hmm, I dunno.

**Comment by pardahlman** [comment]
Viewing the results in detail is called viewing a `Preview`
