### ISSUE TITLE
Use same method for all signalr pushes to frontend

### ISSUE THREAD

**Issue by pardahlman** [wrido/wrido#18]
Today, each message type pushed from backend to frontend invokes a message specific method, for example `ResultsAvailable` is pubished on a method with that name, making it so that the front end needs to bind event handlers for each method type.

```js
connection.on('ResultsAvailable', r => { ... });
```

We should push the messages to the same "method", so that the javascript only needs to register one event handler.

Here's my suggestion:

Call the new "method" for `event`, which will make the front end code read like this

```js
connection.on('event', r => { ... });
```

The event payload could look like this:

```json
{
  "type" : "ResultsAvailable",
  "payload" : {  }
}
```
where `payload` is the actual message. I guess it would be possible to put the payload properties side by side with the `type` property. @Korla what do you think?

**Comment by Korla** [comment]
This sounds like a great change. The frontend convention is to use lowercase types, which may or may not change our feelings on the matter :)

Payload properties can be put next to the type property, the only risk with that being that some payload wanted a type property, or some other property we add to the action metadata down the line.

**Comment by pardahlman** [comment]
With PR #21 merged, it should be possible to update `Wrido.Web` to listen on messages on the `event` channel 🎉

**Comment by Korla** [comment]
PR #22 makes `Wrido.Web` listen to the `event` channel. The duplicate behaviour can be removed in the backend.

**Comment by pardahlman** [comment]
And so #24 removes the old ways of doing this. Closing this issue now, we have to live with title cased events for a little while 🙃
