### ISSUE TITLE
Detailed view toggleable?

### ISSUE THREAD

**Issue by pardahlman** [wrido/wrido#28]
I've been thinking about the detailed view. I like the minimalistic design that is just one large input field with results listing underneath it (decreased cognitive load). Details should be available from within wrido.

So, here's an suggestion. The application configuration object should have a setting for `detailedResult` (name pending 😉) that can have three values:

* `off` meaning that the detailed view is never rendered. Providers in the backend can use this value to decide if it should load detailed data. Frontend can use this value to make sure that the detailed view is never activated. `off` could be a great option if you're running on a metered connection or just don't want to waste bandwidth.
* `lazy` meaning that details will be loaded when the user requests details. The user "requests" details by pressing a configuration enabled hotkey for open detailed view (default could perhaps be right arrow when having a certain result). While the detail view is visible details will be requested as the user "activates" a result. The result can be cached in frontend.
* `auto`, meaning that details will be requested if the detail view is activated while sending queries to the backend.
* `on`, meaning that the providers will load details preemptively. Frontend can use this value to always keep the details view visible. This will probably give the best user experience, but at the cost of bandwidth and compute time. 

Not sure if `lazy` and `auto` can be merged into one or if there is a better way to slice it.

Here's an example of how the configuration object could look like

```json
{
  "shortcuts": {
    "focus" : "alt+space",
    "detailedResultOn" : "right arrow",
    "detailedResultOff" : "left arrow",
  },
  "detailedResult" : "lazy",
  "plugins" : [
    "wrido.plugin.wikipedia"
  ]
}
```

I'm thinking that the layout can take inspiration from Spotlight

![image](https://user-images.githubusercontent.com/1032755/35776707-d47d43f8-09a1-11e8-9e11-abe0740a194f.png)

**Comment by pardahlman** [comment]
I guess that the settings could be grouped like this, too

```json
{
    "detailedResults" : {
        "enable" : "right arrow",
        "disable" : "left arrow",
        "strategy" : "auto"
    }
}
```

Let's settle on the fact that these properties are configurable from the json file rather than how the settings are structured 🤓

**Comment by pardahlman** [comment]
Yes, that's a valid point. Some providers might use rate limited or otherwise "expensive" APIs to enrich a result with more details (or perhaps an result can be enriched multiple times, some of which are expensive and other that aren't). In that case, I think it makes sense for the plugin to have plugin specific configuration that can handle these cases. However, if the detailed view is `off` for the application, no details are going to show and so the plugin should look at this value before loading more data.

**Comment by pardahlman** [comment]
This is a work in progress, but here  a working example of a `previewUri` that is rendered in the preview window.

![preview](https://user-images.githubusercontent.com/1032755/38160997-4e7528c4-34c7-11e8-8818-fcfc31cf4a2c.gif)

**Comment by pardahlman** [comment]
Here's a preview of Spotify's details that does not just iframe some external site, but renders details based on the `result`

![spotify-preview](https://user-images.githubusercontent.com/1032755/38198506-662df50a-368d-11e8-8e94-decffcf02225.gif)

**Comment by dahlman** [comment]
Beautiful!
