### ISSUE TITLE
Build system for front end

### ISSUE THREAD

**Issue by pardahlman** [wrido/wrido#4]
I'm guessing Webpack? ES6 or Typescript?

**Comment by tjoskar** [comment]
I don't know what `wrido` is but go with Typescript, Typescript is always the answer ;)

**Comment by pardahlman** [comment]
@tjoskar 👋 I've also a fan of TS.. but then again with the right tooling (linters, transpiler etc) the differences isn't that great. Or am I wrong? 🤔

**Comment by tjoskar** [comment]
eslist is really sophisticated nowadays but it will never be able to catch errors like accessing non-existent properties, eg.
```js
const myVar = {
  myProp: {
    myNumber: 5
  }
}

myVar.nyProp.myNumber // Error: Cannot read property 'myNumber' of undefined
```

Or prevent you from passing wrong arguments to a function:
```js 
function add(a, b) {
  return a + b
}

add('1', 2) // '12'
```

But most importantly, your IDE/editor can only do a qualified guesswork for typeahead/autocompletion. With typescript/flow you will get documentation right at your fingertips. This speeds up the development many times over (as you already know).

Furthermore, typescript does support ES2017 so you do not need to choose between ES6 and typescript. 

Having said that, typescript ~~[will](https://medium.com/fusebox/do-you-really-need-babel-baa0971f1957)~~ can add some complexity to the build chain and sometimes make the code less readable but it is a totally worth it and as you may know [Babel 7 will support Typescript](https://babeljs.io/blog/2017/09/12/planning-for-7.0#typescript) 🎉 .

Summary; Use javascript if you think it is going to be a small/simple project but if you are planning on using webpack or any other build tool I recommended you to use typescript, on maybe flow.

Let me know if you are planning on building something awesome.

**Comment by pardahlman** [comment]
Alright, @tjoskar - how about a beer next week? I think it's long overdue to catch up anyways! 🍻

**Comment by pardahlman** [comment]
(and thanks for your comments, I think you are making some very valid points 👍 )

**Comment by tjoskar** [comment]
@pardahlman, you've got mail! 🍻

**Comment by Korla** [comment]
I just merged a PR with a create-react-app frontend without Typescript, but it could be complemented by for example https://www.npmjs.com/package/react-scripts-ts to add support for Typescript. I am a decent fan of Typescript, but generally for bigger things, and I find that it works much better with for example Angular than React, and even Redux lends itself to syntaxes which make the typescript compiler (or at least the syntax highlighting in most IDE:s) very sad.
